Pagegoldenbook
WildCodeSchool/tours-0320-php-villa-corsica pull request #22
Opened 2020-06-18 11:48 UTC by AhmadSAFAR

Golden book page

2020-06-18 13:26 UTC, Murihano approved these changes
LGTM !

2020-06-18 13:53 UTC, RomainClair requested changes
The new and index method of the GoldenBookController seems to be the same.
You should avoir duplicate code.

2020-06-18 13:53 UTC, RomainClair commented on src/Form/GoldenBookType.php
> +            ->add('villa', null, ['choice_label'=>'name'])
You should Type your Form fields and...
This one should probably be an EntityType.

2020-06-22 08:22 UTC, louismarquenet approved these changes

2020-06-22 09:12 UTC, RomainClair approved these changes

2020-06-22 09:12 UTC, merged